export const LABS_REFERENCE = [
  {
    category: 'CBC',
    values: [
      { name: 'WBC', value: '4.5–11.0', unit: '×10³/µL' },
      { name: 'RBC', value: '4.2–5.4 (F), 4.7–6.1 (M)', unit: '×10⁶/µL' },
      { name: 'Hemoglobin', value: '12–16 (F), 14–18 (M)', unit: 'g/dL' },
      { name: 'Hematocrit', value: '37–47% (F), 42–52% (M)', unit: '%' },
      { name: 'MCV', value: '80–100', unit: 'fL' },
      { name: 'MCH', value: '27–33', unit: 'pg' },
      { name: 'MCHC', value: '32–36', unit: 'g/dL' },
      { name: 'RDW', value: '11.5–14.5', unit: '%' },
      { name: 'Platelets', value: '150–400', unit: '×10³/µL' },
      { name: 'Neutrophils', value: '45–75', unit: '%' },
      { name: 'Lymphocytes', value: '16–46', unit: '%' },
      { name: 'Monocytes', value: '4–11', unit: '%' },
      { name: 'Eosinophils', value: '0–6', unit: '%' },
      { name: 'Basophils', value: '0–2', unit: '%' },
    ],
  },
  {
    category: 'BMP / CMP',
    values: [
      { name: 'Sodium (Na⁺)', value: '136–145', unit: 'mEq/L' },
      { name: 'Potassium (K⁺)', value: '3.5–5.0', unit: 'mEq/L' },
      { name: 'Chloride (Cl⁻)', value: '98–106', unit: 'mEq/L' },
      { name: 'Bicarbonate (HCO₃⁻)', value: '22–29', unit: 'mEq/L' },
      { name: 'BUN', value: '7–25', unit: 'mg/dL' },
      { name: 'Creatinine', value: '0.6–1.2', unit: 'mg/dL' },
      { name: 'Glucose (fasting)', value: '70–99', unit: 'mg/dL' },
      { name: 'Calcium', value: '8.5–10.5', unit: 'mg/dL' },
      { name: 'Magnesium', value: '1.7–2.2', unit: 'mg/dL' },
      { name: 'Phosphate', value: '2.5–4.5', unit: 'mg/dL' },
      { name: 'Albumin', value: '3.5–5.0', unit: 'g/dL' },
      { name: 'Total protein', value: '6.0–8.0', unit: 'g/dL' },
      { name: 'Uric acid', value: '2.4–6.0 (F), 3.4–7.0 (M)', unit: 'mg/dL' },
    ],
  },
  {
    category: 'LFTs',
    values: [
      { name: 'ALT (SGPT)', value: '7–56', unit: 'U/L' },
      { name: 'AST (SGOT)', value: '10–40', unit: 'U/L' },
      { name: 'Alkaline phosphatase', value: '44–147', unit: 'U/L' },
      { name: 'GGT', value: '9–48', unit: 'U/L' },
      { name: 'Total bilirubin', value: '0.1–1.2', unit: 'mg/dL' },
      { name: 'Direct bilirubin', value: '0.0–0.3', unit: 'mg/dL' },
      { name: 'Indirect bilirubin', value: '0.1–1.0', unit: 'mg/dL' },
      { name: 'PT', value: '11–13.5', unit: 'sec' },
      { name: 'INR', value: '0.8–1.2', unit: '' },
    ],
  },
  {
    category: 'Coagulation',
    values: [
      { name: 'PT', value: '11–13.5', unit: 'sec' },
      { name: 'PTT / aPTT', value: '25–35', unit: 'sec' },
      { name: 'INR', value: '0.8–1.2', unit: '' },
      { name: 'Thrombin time', value: '14–19', unit: 'sec' },
      { name: 'Fibrinogen', value: '200–400', unit: 'mg/dL' },
      { name: 'D-dimer', value: '<0.5', unit: 'µg/mL FEU' },
      { name: 'Bleeding time', value: '2–7', unit: 'min' },
    ],
  },
  {
    category: 'ABG',
    values: [
      { name: 'pH', value: '7.35–7.45', unit: '' },
      { name: 'PaCO₂', value: '35–45', unit: 'mm Hg' },
      { name: 'PaO₂', value: '75–100', unit: 'mm Hg' },
      { name: 'HCO₃⁻', value: '22–26', unit: 'mEq/L' },
      { name: 'O₂ saturation', value: '95–100', unit: '%' },
      { name: 'Base excess', value: '-2 to +2', unit: 'mEq/L' },
    ],
  },
  {
    category: 'UA',
    values: [
      { name: 'pH', value: '4.5–8.0', unit: '' },
      { name: 'Specific gravity', value: '1.005–1.030', unit: '' },
      { name: 'Protein', value: '<150', unit: 'mg/day' },
      { name: 'Glucose', value: 'Negative', unit: '' },
      { name: 'Ketones', value: 'Negative', unit: '' },
      { name: 'Blood/Hemoglobin', value: 'Negative', unit: '' },
      { name: 'WBC', value: '<5', unit: '/hpf' },
      { name: 'RBC', value: '<3', unit: '/hpf' },
      { name: 'Creatinine clearance', value: '88–128 (F), 97–137 (M)', unit: 'mL/min' },
    ],
  },
  {
    category: 'CSF',
    values: [
      { name: 'Opening pressure', value: '70–180', unit: 'mm H₂O' },
      { name: 'WBC', value: '0–5', unit: 'cells/µL' },
      { name: 'RBC', value: '0', unit: 'cells/µL' },
      { name: 'Protein', value: '15–60', unit: 'mg/dL' },
      { name: 'Glucose', value: '45–80', unit: 'mg/dL' },
      { name: 'CSF:serum glucose', value: '>0.6', unit: '' },
      { name: 'Chloride', value: '116–130', unit: 'mEq/L' },
    ],
  },
  {
    category: 'Lipids',
    values: [
      { name: 'Total cholesterol', value: '<200', unit: 'mg/dL' },
      { name: 'LDL', value: '<100 (optimal)', unit: 'mg/dL' },
      { name: 'HDL', value: '>60 (optimal)', unit: 'mg/dL' },
      { name: 'Triglycerides', value: '<150', unit: 'mg/dL' },
    ],
  },
  {
    category: 'Thyroid',
    values: [
      { name: 'TSH', value: '0.4–4.0', unit: 'mIU/L' },
      { name: 'Free T4', value: '0.8–1.8', unit: 'ng/dL' },
      { name: 'Free T3', value: '2.3–4.2', unit: 'pg/mL' },
      { name: 'Total T4', value: '5.0–12.0', unit: 'µg/dL' },
    ],
  },
  {
    category: 'Cardiac',
    values: [
      { name: 'Troponin I', value: '<0.04', unit: 'ng/mL' },
      { name: 'Troponin T', value: '<0.01', unit: 'ng/mL' },
      { name: 'CK-MB', value: '<5', unit: 'ng/mL' },
      { name: 'BNP', value: '<100', unit: 'pg/mL' },
      { name: 'NT-proBNP', value: '<125', unit: 'pg/mL' },
      { name: 'CRP (hs)', value: '<1.0 (low risk)', unit: 'mg/L' },
    ],
  },
];
