// All values sourced from USMLE reference sheet (SI intervals included where provided)
export const LABS_REFERENCE = [
  {
    category: 'Electrolytes',
    values: [
      { name: 'Sodium (Na⁺)',        value: '136–146 mEq/L',           si: '136–146 mmol/L' },
      { name: 'Potassium (K⁺)',      value: '3.5–5.0 mEq/L',           si: '3.5–5.0 mmol/L' },
      { name: 'Chloride (Cl⁻)',      value: '95–105 mEq/L',            si: '95–105 mmol/L' },
      { name: 'Bicarbonate (HCO₃⁻)', value: '22–28 mEq/L',            si: '22–28 mmol/L' },
      { name: 'BUN (Urea nitrogen)', value: '7–18 mg/dL',              si: '2.5–6.4 mmol/L' },
      { name: 'Creatinine',          value: '0.6–1.2 mg/dL',           si: '53–106 µmol/L' },
      { name: 'Glucose (fasting)',   value: '70–100 mg/dL',            si: '3.8–5.6 mmol/L' },
      { name: 'Glucose (random)',    value: '<140 mg/dL',              si: '<7.77 mmol/L' },
      { name: 'Calcium',             value: '8.4–10.2 mg/dL',          si: '2.1–2.6 mmol/L' },
      { name: 'Magnesium (Mg²⁺)',    value: '1.5–2.0 mg/dL',           si: '0.75–1.0 mmol/L' },
      { name: 'Phosphorus (inorg.)', value: '3.0–4.5 mg/dL',           si: '1.0–1.5 mmol/L' },
    ],
  },
  {
    category: 'Hepatic / LFTs',
    values: [
      { name: 'ALT',                 value: '10–40 U/L' },
      { name: 'AST',                 value: '12–38 U/L' },
      { name: 'Alkaline phosphatase',value: '25–100 U/L' },
      { name: 'Bilirubin, total',    value: '0.1–1.0 mg/dL',           si: '2–17 µmol/L' },
      { name: 'Bilirubin, direct',   value: '0.0–0.3 mg/dL',           si: '0–5 µmol/L' },
      { name: 'Proteins, total',     value: '6.0–7.8 g/dL',            si: '60–78 g/L' },
      { name: 'Albumin',             value: '3.5–5.5 g/dL',            si: '35–55 g/L' },
      { name: 'Globulin',            value: '2.3–3.5 g/dL',            si: '23–35 g/L' },
    ],
  },
  {
    category: 'Other Serum',
    values: [
      { name: 'Amylase',             value: '25–125 U/L' },
      { name: 'Lipase',              value: '13–60 U/L' },
      { name: 'CrCl (M)',            value: '97–137 mL/min' },
      { name: 'CrCl (F)',            value: '88–128 mL/min' },
      { name: 'Creatine kinase (M)', value: '25–90 U/L' },
      { name: 'Creatine kinase (F)', value: '10–70 U/L' },
      { name: 'LDH',                 value: '45–200 U/L' },
      { name: 'Osmolality',          value: '275–295 mOsmol/kg H₂O' },
      { name: 'Troponin I',          value: '≤0.04 ng/mL',             si: '≤0.04 µg/L' },
      { name: 'Uric acid',           value: '3.0–8.2 mg/dL',           si: '0.18–0.48 mmol/L' },
    ],
  },
  {
    category: 'Lipids',
    values: [
      { name: 'Total cholesterol (normal)', value: '<200 mg/dL',       si: '<5.2 mmol/L' },
      { name: 'Total cholesterol (high)',   value: '>240 mg/dL',       si: '>6.2 mmol/L' },
      { name: 'HDL',                        value: '40–60 mg/dL',      si: '1.0–1.6 mmol/L' },
      { name: 'LDL',                        value: '<160 mg/dL',       si: '<4.2 mmol/L' },
      { name: 'Triglycerides (normal)',     value: '<150 mg/dL',       si: '<1.70 mmol/L' },
      { name: 'Triglycerides (borderline)', value: '151–199 mg/dL',    si: '1.71–2.25 mmol/L' },
    ],
  },
  {
    category: 'Iron Studies',
    values: [
      { name: 'Ferritin (M)',        value: '20–250 ng/mL',            si: '20–250 µg/L' },
      { name: 'Ferritin (F)',        value: '10–120 ng/mL',            si: '10–120 µg/L' },
      { name: 'Iron (M)',            value: '65–175 µg/dL',            si: '11.6–31.3 µmol/L' },
      { name: 'Iron (F)',            value: '50–170 µg/dL',            si: '9.0–30.4 µmol/L' },
      { name: 'TIBC',               value: '250–400 µg/dL',           si: '44.8–71.6 µmol/L' },
      { name: 'Transferrin',        value: '200–360 mg/dL',           si: '2.0–3.6 g/L' },
    ],
  },
  {
    category: 'Endocrine',
    values: [
      { name: 'FSH (M)',             value: '4–25 mIU/mL',             si: '4–25 IU/L' },
      { name: 'FSH (F, premenop.)',  value: '4–30 mIU/mL',             si: '4–30 IU/L' },
      { name: 'FSH (F, midcycle)',   value: '10–90 mIU/mL',            si: '10–90 IU/L' },
      { name: 'FSH (F, postmenop.)', value: '40–250 mIU/mL',           si: '40–250 IU/L' },
      { name: 'LH (M)',              value: '6–23 mIU/mL',             si: '6–23 IU/L' },
      { name: 'LH (F, follicular)',  value: '5–30 mIU/mL',             si: '5–30 IU/L' },
      { name: 'LH (F, midcycle)',    value: '75–150 mIU/mL',           si: '75–150 IU/L' },
      { name: 'LH (F, postmenop.)',  value: '30–200 mIU/mL',           si: '30–200 IU/L' },
      { name: 'GH (fasting)',        value: '<5 ng/mL',                si: '<5 µg/L' },
      { name: 'GH (provocative)',    value: '>7 ng/mL',                si: '>7 µg/L' },
      { name: 'Prolactin (M)',       value: '<17 ng/mL',               si: '<17 µg/L' },
      { name: 'Prolactin (F)',       value: '<25 ng/mL',               si: '<25 µg/L' },
      { name: 'Cortisol (0800 h)',   value: '5–23 µg/dL',              si: '138–635 nmol/L' },
      { name: 'Cortisol (1600 h)',   value: '3–15 µg/dL',              si: '82–413 nmol/L' },
      { name: 'Cortisol (2000 h)',   value: '<50% of 0800 h value' },
      { name: 'TSH',                 value: '0.4–4.0 µU/mL',           si: '0.4–4.0 mIU/L' },
      { name: 'T3 (total)',          value: '100–200 ng/dL',           si: '1.5–3.1 nmol/L' },
      { name: 'T3 resin uptake',     value: '25%–35%',                 si: '0.25–0.35' },
      { name: 'T4 (total)',          value: '5–12 µg/dL',              si: '64–155 nmol/L' },
      { name: 'Free T4',             value: '0.9–1.7 ng/dL',           si: '12.0–21.9 pmol/L' },
      { name: 'Thyroidal ¹²³I uptake', value: '8%–30%/24 h',          si: '0.08–0.30/24 h' },
      { name: 'Intact PTH',          value: '10–60 pg/mL',             si: '10–60 ng/L' },
      { name: '17-OH corticosteroids (M)', value: '3.0–10.0 mg/24 h', si: '8.2–27.6 µmol/24 h' },
      { name: '17-OH corticosteroids (F)', value: '2.0–8.0 mg/24 h',  si: '5.5–22.0 µmol/24 h' },
      { name: '17-Ketosteroids (M)', value: '8–20 mg/24 h',            si: '28–70 µmol/24 h' },
      { name: '17-Ketosteroids (F)', value: '6–15 mg/24 h',            si: '21–52 µmol/24 h' },
      { name: 'Hemoglobin A1c',      value: '≤6%',                     si: '≤42 mmol/mol' },
    ],
  },
  {
    category: 'Immunoglobulins',
    values: [
      { name: 'IgA',  value: '76–390 mg/dL',  si: '0.76–3.90 g/L' },
      { name: 'IgE',  value: '0–380 IU/mL',   si: '0–380 kIU/L' },
      { name: 'IgG',  value: '650–1500 mg/dL', si: '6.5–15.0 g/L' },
      { name: 'IgM',  value: '50–300 mg/dL',  si: '0.5–3.0 g/L' },
    ],
  },
  {
    category: 'ABG (Room Air)',
    values: [
      { name: 'PO₂',  value: '75–105 mm Hg',  si: '10.0–14.0 kPa' },
      { name: 'PCO₂', value: '33–45 mm Hg',   si: '4.4–5.9 kPa' },
      { name: 'pH',   value: '7.35–7.45' },
    ],
  },
  {
    category: 'CSF',
    values: [
      { name: 'Cell count',      value: '0–5/mm³',         si: '0–5 × 10⁶/L' },
      { name: 'Chloride',        value: '118–132 mEq/L',   si: '118–132 mmol/L' },
      { name: 'Gamma globulin',  value: '3%–12% of total proteins', si: '0.03–0.12' },
      { name: 'Glucose',         value: '40–70 mg/dL',     si: '2.2–3.9 mmol/L' },
      { name: 'Pressure',        value: '70–180 mm H₂O' },
      { name: 'Proteins, total', value: '<40 mg/dL',       si: '<0.40 g/L' },
    ],
  },
  {
    category: 'CBC',
    values: [
      { name: 'Hematocrit (M)',    value: '41%–53%',              si: '0.41–0.53' },
      { name: 'Hematocrit (F)',    value: '36%–46%',              si: '0.36–0.46' },
      { name: 'Hemoglobin (M)',    value: '13.5–17.5 g/dL',       si: '135–175 g/L' },
      { name: 'Hemoglobin (F)',    value: '12.0–16.0 g/dL',       si: '120–160 g/L' },
      { name: 'MCH',              value: '25–35 pg/cell',         si: '0.39–0.54 fmol/cell' },
      { name: 'MCHC',             value: '31%–36% Hb/cell' },
      { name: 'MCV',              value: '80–100 µm³',            si: '80–100 fL' },
      { name: 'WBC',              value: '4500–11,000/mm³',       si: '4.5–11.0 × 10⁹/L' },
      { name: 'Neutrophils (seg)', value: '54%–62%',              si: '0.54–0.62' },
      { name: 'Neutrophils (band)',value: '3%–5%',                si: '0.03–0.05' },
      { name: 'Lymphocytes',      value: '25%–33%',               si: '0.25–0.33' },
      { name: 'Monocytes',        value: '3%–7%',                 si: '0.03–0.07' },
      { name: 'Eosinophils',      value: '1%–3%',                 si: '0.01–0.03' },
      { name: 'Basophils',        value: '0%–0.75%',              si: '0.00–0.0075' },
      { name: 'Platelets',        value: '150,000–400,000/mm³',   si: '150–400 × 10⁹/L' },
      { name: 'Reticulocytes',    value: '0.5%–1.5%',             si: '0.005–0.015' },
      { name: 'RBC (M)',          value: '4.3–5.9 million/mm³',   si: '4.3–5.9 × 10¹²/L' },
      { name: 'RBC (F)',          value: '3.5–5.5 million/mm³',   si: '3.5–5.5 × 10¹²/L' },
      { name: 'ESR (M)',          value: '0–15 mm/h' },
      { name: 'ESR (F)',          value: '0–20 mm/h' },
      { name: 'CD4⁺ T-lymphocytes', value: '≥500/mm³',           si: '≥0.5 × 10⁹/L' },
    ],
  },
  {
    category: 'Coagulation',
    values: [
      { name: 'PT',         value: '11–15 seconds' },
      { name: 'PTT / aPTT', value: '25–40 seconds' },
      { name: 'D-Dimer',    value: '≤250 ng/mL',  si: '≤1.4 nmol/L' },
    ],
  },
  {
    category: 'Urine',
    values: [
      { name: 'Calcium',        value: '100–300 mg/24 h',      si: '2.5–7.5 mmol/24 h' },
      { name: 'Osmolality',     value: '50–1200 mOsmol/kg H₂O' },
      { name: 'Oxalate',        value: '8–40 µg/mL',           si: '90–445 µmol/L' },
      { name: 'Proteins, total', value: '<150 mg/24 h',        si: '<0.15 g/24 h' },
    ],
  },
];
